name: echo
description: echo

inputs:
  greeting:
    description: 'Greeting message'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.greeting }}
  env:
    SOME_VAR: "this is secret"
