name: CI

on:
  push:
    paths:
      - .github/actions/node-echo/**
      - .github/workflows/ci_2.yaml

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/node-echo
