name: CI

on:
  pull_request:
    paths:
      - .github/actions/node-echo/**
      - .github/workflows/ci_2.yaml

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.event.pull_request.base.sha }}"
      - uses: ./.github/actions/node-echo
